---
title: "Discussion 4"
author: "Duubar Villalobos Jimenez"
date: "February 21, 2018"
output:
  prettydoc::html_pretty:
    highlight: github
    theme: leonids
    toc: yes
  pdf_document: default
  html_document: default
subtitle: CUNY MSDS DATA 605
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#.libPaths()
#.libPaths( c( .libPaths(), "/home/mydvadmin/anaconda3/lib/R/library") )

#install.packages("install.load")
library(install.load)
install_load("pracma", "prettydoc")
```

# C26 † Page 443

**Book:** Beezer: A First Course in Linear Algebra

## Exercise

Verify that the function below is a linear transformation.

$$T:P_2 \rightarrow C^2,   T \left( a + bx + cx^2 \right) = \begin{pmatrix}2a - b\\ b + c\end{pmatrix}$$

### Solution

For this, we need to verify the two defining conditions of a linear transformation; that is:

+ 1. $T(x + y) = T(x) + T(y)$

+ 2. $T( \alpha x) =  \alpha T(x)$


**1.** First let's work on **(1)** $T(x + y) = T(x) + T(y)$.

$$T(x + y) = T \left((a_1 + b_1x + c_1x^2) + (a_2 + b_2x + c_2x^2)\right)$$

$$T(x + y) = T \left((a_1 + a_2) + (b_1 + b_2)x  + (c_1+ c_2)x^2\right)$$

Let's define as follows:

$a = a_1 + a_2$

$b = b_1 + b_2$

$c = c_1 + c_2$

By making a substitution; we have as follows:

$$T(x + y) = T \left((a) + (b)x  + (c)x^2\right)$$
And by our given problem, we have as follows:

$$T \left( a + bx + cx^2 \right) = \begin{pmatrix}2a - b\\ b + c\end{pmatrix}$$

And by substituting back we have:

$$T(x + y) =\begin{pmatrix}2(a_1 + a_2) - ( b_1 + b_2)\\ ( b_1 + b_2) +  (c_1 + c_2)\end{pmatrix}$$

$$T(x + y) =\begin{pmatrix}(2a_1 + 2a_2) - ( b_1 + b_2)\\ ( b_1 + b_2) +  (c_1 + c_2)\end{pmatrix}$$

$$T(x + y) =\begin{pmatrix}(2a_1 - b_1) + (2a_2 - b_2)\\ ( b_1 + c_1) +  (b_2 + c_2)\end{pmatrix}$$

$$T(x + y) =\begin{pmatrix}(2a_1 - b_1) \\ ( b_1 + c_1) \end{pmatrix} + \begin{pmatrix} (2a_2 - b_2) \\ (b_2 + c_2)\end{pmatrix}$$

$$T(x + y) =\begin{pmatrix}2a_1 - b_1 \\  b_1 + c_1 \end{pmatrix} + \begin{pmatrix} 2a_2 - b_2 \\ b_2 + c_2\end{pmatrix}$$

$$T(x + y) = T \left( a_1 + b_1x + c_1x^2 \right) + T \left( a_2 + b_2x + c_2x^2 \right)$$


$$T(x + y) = T(x) + T(y)$$


This proof the first part of the definition is met.



**2.** Now, I will focus on **(2)** $T( \alpha x) =  \alpha T(x)$.

$$T(\alpha x) = T \left( \alpha (a_1 + b_1x + c_1x^2) \right) $$

$$T(\alpha x) = T \left(  \alpha a_1 + \alpha b_1x + \alpha c_1x^2 \right) $$

Let's define as follows:

$a = \alpha a_1$

$b = \alpha b_1$

$c = \alpha c_1$

And by making a substitution we get:

$$T(\alpha x) = T \left( a + bx + cx^2 \right) $$

Given our original equation, we have as follows:

$$T(\alpha x) = \begin{pmatrix}2a - b\\ b + c\end{pmatrix}$$

By replacing back our previous definitions, we get as follows:

$$T(\alpha x) = \begin{pmatrix}2 \alpha a_1 - \alpha b_1\\ \alpha b_1 +\alpha  c_1\end{pmatrix}$$

$$T(\alpha x) = \begin{pmatrix} \alpha (2a_1 - b_1)\\ \alpha (b_1 + c_1)\end{pmatrix}$$


$$T(\alpha x) = \alpha \begin{pmatrix}  2a_1 - b_1\\ b_1 + c_1\end{pmatrix}$$

$$T(\alpha x) = \alpha T \left( a + bx + cx^2 \right)$$

$$T(\alpha x) = \alpha T(x)$$

This demonstrates that the second equation is met.

### Conclusion: 

$$T:P_2 \rightarrow C^2,   T \left( a + bx + cx^2 \right) = \begin{pmatrix}2a - b\\ b + c\end{pmatrix}$$

The above function is a linear transformation since the two defining equations are met.




